llm:
  enabled: false
  provider: openai
  model: gpt-4o-mini
  temperature: 0.0
  max_retries: 2
  timeout: 60

chunking:
  max_chars: 4000
  overlap: 400

languages:
  default_set:
    - bg
    - hr
    - cs
    - da
    - nl
    - en
    - et
    - fi
    - fr
    - de
    - el
    - hu
    - ga
    - it
    - lv
    - lt
    - mt
    - pl
    - pt
    - ro
    - sk
    - sl
    - es
    - sv
    - tr
    - ru
    - uk
    - ar
    - zh-CN
    - ja
    - ko
    - no
    - sr
    - bs

prompts:
  domain_classification: |
    You are an experienced localisation strategist. Review the text below and respond with JSON containing
    "domain" (string), "subdomains" (array), and "related" (array) capturing the technical or subject-matter
    focus of the material. Text:
    {payload}
  styleguide_refinement: |
    You are a senior localisation PM. Refine the provided style guide JSON, enriching empty fields while
    preserving the structure. Respond with JSON only.

external_tools:
  terminology_url: "https://termtool.streamlit.app"
